### PR TITLE
Naive optimization of skipping any json path tracking when no json path keys are defined

### PR DESCRIPTION
**Pull request by gavlyukovskiy**
Not sure if we should go with this or get something more elaborate

### CODE REVIEW

**Comment by Breus** [comment]
Oh lol 😂  Yea, I think we are aligned (saw this PR after the previous one)

@donavdey

**Comment by gavlyukovskiy** [comment]
@Breus I think we might wait until state machine proposal is implemented. It would be much easier to do it there than having a (one more) layer of if statements. 
But this shows that we are getting ~30% slower on tracking the JsonPath on top of already losing about ~30% for supporting new API options.

**Comment by donavdey** [comment]
We can still track current jsonpath, but skip querying the trie for the json path key as this is the most expensive operation. That is, on `trackJsonPath` option disabled always return an empty iterator over segments and avoid making `searchForJsonPathKey` call in general. What do you think? @gavlyukovskiy @Breus

**Comment by gavlyukovskiy** [comment]
@donavdey it's actually tracking that takes the most time, not the search. I've been profiling it a couple of times and screenshot in https://github.com/Breus/json-masker/pull/58 also captured it. As you see there, it's roughly 30% for tracking and maybe 10% for trie lookup

**Comment by donavdey** [comment]
@gavlyukovskiy I see now, this makes sense. I wonder if the track method can be optimized before focusing on the lookup optimization

**Comment by gavlyukovskiy** [comment]
@breus @donavdey I'll close this one as it won't be compatible with #62. It was useful to know that we're loosing ~30% perf with JsonPath logic, so let's keep this in mind for future.

**Pull request closed without merging**
